### ISSUE TITLE
Props formatting

### ISSUE THREAD

**Issue by lajbel** [g-plane/markup_fmt#10]
I love how dprint handles the formatting in JSX with the component's props, for example

```jsx
const Component = () => {
    return (
        <Badge color="red" size="xs">
            {"@" + username}
        </Badge>
    )
}
```

This code formats to this: (the same)
```js
const Component = () => {
    return (
        <Badge color="red" size="xs">
            {"@" + username}
        </Badge>
    )
}
```

And this code:
```jsx
const Component = () => {
    return (
        <Badge
            color="red"
            size={25}
        >
            {"@" + username}
        </Badge>
    );
};
```

to this (also the same)
```jsx
const Component = () => {
    return (
        <Badge
            color="red"
            size={25}
        >
            {"@" + username}
        </Badge>
    );
};
```

When you have 2 props, you can select use a new line on every prop, or put it in the same line, this avoid this ugly prettier problem:

Input
```jsx
<div>
    <Card name="John Doe" age={25} imageUrl="myImageHost.com/x"/>
    <Card name="John Doe" age={25} imageUrl="myImageHost.com/x1242141245939519659"/>
</div>
```

Output
```jsx
<div>
    <Card name="John Doe" age={25} imageUrl="myImageHost.com/x" />

    <Card
        name="John Doe"
        age={25}
        imageUrl="myImageHost.com/x1242141245939519659"
    />
</div>;
```

With no option of be like this:
```jsx
<div>
    <Card 
        name="John Doe" 
        age={25} 
        imageUrl="myImageHost.com/x" 
    />

    <Card
        name="John Doe"
        age={25}
        imageUrl="myImageHost.com/x1242141245939519659"
    />
</div>;
```

This plugin has the same problem, and I would like to have an option like mantain the user selection of new lines in props. Thank you for this awesome plugin! I like to use it with Astro

**Comment by g-plane** [comment]
I may add a new option to support this style, but it will be disabled by default to avoid breaking. Does this make sense?

**Comment by g-plane** [comment]
With the code example you gave:

```astro
<div>
    <Card name="John Doe" age={25} imageUrl="myImageHost.com/x"/>
    <Card name="John Doe" age={25} imageUrl="myImageHost.com/x1242141245939519659"/>
</div>
```

The first `<Card>` component won't be splitted into different lines: [playground](https://dprint.dev/playground/#code/DwEwlgbgfAUABAuwDCBDATiOA7VBbAUwF4AiAKQHsALbOAEQoJLlQHNiBvAJgFYBfOGDxsCAVXQAbUngCeASWHsAEhQDOAFwB0AYwp4A9AA9m+2PEQoMIc4kS5CpSjXqMSN2y3ZFu-d7aEi4lIksgoiKho6ekYAjFwALFwx8XHxPACcAMzpPDHpAGwZbramMMD64NAA3EA/plugin/BYFxAcGcC4HpfAGwK4HMCWA7SA6AJuAE5Yj4CmAbrKgLRICGmZsAtvYQNbLgD6AZixA0KABhwBWHAEYcAd3qQWQA)

What's the problem?

**Comment by g-plane** [comment]
I will add a new option for this, but it will be disabled by default to avoid breaking. Does it make sense?

**Comment by g-plane** [comment]
[v0.6.0](https://github.com/g-plane/markup_fmt/releases/tag/v0.6.0) is released. You don't need to update your configuration and now it formats as you expected.

Feel free to open new issues if you find bugs, also don't forget to give it a star and recommend this project to others.
