### ISSUE TITLE
Add Vento support

### ISSUE THREAD

**Issue by wrapperup** [g-plane/markup_fmt#11]
Hi, thanks for making this plugin! It's hard to find a good formatter for HTML templates.

Any chance that support for Vento could be added? https://github.com/ventojs/vento

If not, it would be nice to map filetypes to template types (ie, map `.vto` to `Jinja` to get some formatting), and add the ability to preserve whitespace around mustaches/tags/blocks.

Thanks!

**Comment by g-plane** [comment]
You can map file associations in dprint config.

**Comment by wrapperup** [comment]
> You can map file associations in dprint config.

Right, but it only lets you map it to the plugin. It will format it as an HTML file and not as a jinja-like template.
