### ISSUE TITLE
Tag + text wrapping option request

### ISSUE THREAD

**Issue by f11xter** [g-plane/markup_fmt#16]
First a thank you.

I switched to markup_fmt and dprint because I dislike the way Prettier formats void tags, and I've been really enjoying the experience, so thank you very much for making this.

Now the question.

markup_fmt wraps space-sensitive tags with long properties + short text content differently to how it wraps them with short properties + long text:

```html
<a
  href="quite-a-long-url-that-just-keeps-going"
>short text</a>

<a href="not-a-long-url">but a long piece of
  text that wraps</a>
```

I find this a little confusing to read.

Would it be possible to implement an option that's closer to (what I believe is) Prettier's behaviour?

```html
<a  href="quite-a-long-url-that-just-keeps-going"
  >short text</a
>

<a href="not-a-long-url"
  >but a long piece of text that wraps</a
>
```

or a compromise between the two?

```html
<a
  href="quite-a-long-url-that-just-keeps-going"
>short text</a>

<a href="not-a-long-url"
>but a long piece of text that wraps</a>
```

**Comment by g-plane** [comment]
> because I dislike the way Prettier formats void tags

Me too, so I made this.

---

Personally I prefer the second one, but it may conflict with the `closingBracketSameLine` option.

**Comment by f11xter** [comment]
If by the second one you mean the compromise, I agree.

It probably would conflict, so perhaps it could only be activated when `closingBracketSameLine` is false, since presumably users with it set to true wouldn't want the proposed changes anyway.

```html
<!-- closingBracketSameLine false -->
<span
  class=""
  style=""
>retains the current default behaviour</span>

<span class="some long class"
>uses proposed behaviour</span>

<!-- closingBracketSameLine true -->
<span
  class=""
  style="">retains the current
  default behaviour</span>

<span class="some long class">retains
  the current default behaviour</span>
```

**Comment by g-plane** [comment]
Yes, we're on the same idea.
