### ISSUE TITLE
format quote in typescript as single quote in attrs

### ISSUE THREAD

**Issue by clouds56** [g-plane/markup_fmt#18]
```vue
<template>
  <div v-if="label = 'a'"></div>
</template>
```
is now formatted to
```vue
<template>
  <div v-if='label = "a"'></div>
</template>
```
Is it anyway to keep it as is? I don't want to change my typescript config `"quoteStyle": "preferDouble"`.

**Comment by g-plane** [comment]
No. markup_fmt can't do anything with the code in attribute value, and markup_fmt just sends this code to "dprint-plugin-typescript" and let it format.
