### ISSUE TITLE
[BUG] `*.selfClosing` doesn't work well

### ISSUE THREAD

**Issue by so1ovu** [g-plane/markup_fmt#2]
The rule of `*.selfClosing` says when I set it to `true`, the tag will be formatted as `<div />`.

But actually it will be formatted as `<div  />`, so that there are two space in the tag which one is redundant.

I don't know if it should be like that or it's a bug.

Case following:

input:

```html
<div />
<div></div>
```

output:
```html
<div  /> <!-- an extra space in the tag -->
<div  />
```

Here comes my `markup` config:

```json
"markup": {
    "closingBracketSameLine": true,
    "component.selfClosing": true,

    "formatComments": true,

    "html.void.selfClosing": true,
    "html.normal.selfClosing": true,

    "mathml.selfClosing": true,
    "maxAttrsPerLine": 1,

    "printWidth": 88,

    "svg.selfClosing": true,

    "vBindStyle": "short",
    "vForDelimiterStyle": "in",
    "vOnStyle": "short",
    "vSlotStyle": "short"
}
```

**Comment by so1ovu** [comment]
Ok, now I know the reason why it works like that. Because of the `maxAttrsPerLine`, when it was set to a number, tag will be formatted as that, and once I set it to `null`, everything will be ok.

**Comment by g-plane** [comment]
Thanks for reporting.
