### ISSUE TITLE
HTML escaping in Vue cannot be formatted.

### ISSUE THREAD

**Issue by magic-akari** [g-plane/markup_fmt#20]
## dprint.json

```json
{
  "excludes": [
    "**/node_modules"
  ],
  "plugins": [
    "https://plugins.dprint.dev/typescript-0.90.4.wasm",
    "https://plugins.dprint.dev/g-plane/markup_fmt-v0.7.0.wasm"
  ]
}
```

## App.vue
```vue
<script setup>
import { ref } from "vue";
const content = ref("");
</script>

<template>
  <button @click="content +=      &#x27;{&quot;hello&quot;: &quot;I\&#x27;m a button!&quot;}&#x27;">click {{ content }}</button>
</template>
```

## Expected result
formatted without issue

## Actual result
```
Error formatting /Users/akari/Developer/my-vue-app/src/App.vue. Message: [markup_fmt] failed to format code with external formatter: `<>{content +=      &#x27;{&quot;hello&quot;: &quot;I\&#x27;m a button!&quot;}&#x27;}</>`:
Expected ',', got '+=' at file:///expr.tsx:1:12

  <>{content +=      &#x27;{&quot;hello&quot;: &quot;I\&#x27;m a button!&quot;}&#x27;}</>
             ~~
Had 1 error formatting.
```

## Replication Steps

Replication Steps

1. Download [this compressed package](https://github.com/g-plane/markup_fmt/files/15126084/my-vue-app-0.0.0.tgz) and extract it, then enter the directory. 
2. Run `pnpm i` and `pnpm dev` or `pnpm build` to ensure the code can run correctly.
3. Run `pnpm fmt` to observe the formatting situation.

**Comment by g-plane** [comment]
Fun fact: Prettier can't format this. ([playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAzmATgSwA4wAE6cMArngHwA6UOAtnhFkcIVnAGaEC+hnWCPULUQANzJxRAblqQo6IvPixCAXnZcAFKNEBKWVFQB6TLgI0otVPEYAbAIbxLhQqgBGZGDGiEAAmB2OGAA1mqiyghEANQarvEAZADEAB4ATADs0sAJAI5kEDDSABZwdnYQeQVFSIRVhdIAktTUyelZwg6Ent7QAIT1RTxtmbIglIHBIYTAbJGqPDwmPT5Qlia2eI7OIAA0IBAEONDoyKAOWIIA7gAKFwinKA52Vw4Anqf77lgOoaQAyg56HAADI4KBwZCcZ4kL4-P4wf54X7ggDmyBgWEk+xI9BwGKxcH2cBSeDguGBsGeABVyVALjg4I9oXZYSB0Gi7HAAIrVSFIFlsgBW6BS-05PL5UJhRJA+UKcBugjwjxADnQAFoIXAACa6vYgTEOHBBKCogDCQnoDmQavKBo5Zq5AEFvLgeoryWCIdLWbLijB6HYAOrFHDwdDIsBwf4PcM4MTht62sDoT7iSSNKB62D-bD4GDO7P-GBvLm+tl4QQkYM-PC2qtM8liSH7cEkFhKhyo60V2XIrAd20SVsgKvgmDBnA6mDFZAADgADPsOPkcBwuz2bQKZfsYA53FOZ3OkGl9mQSNSD8zdyA4PR3Lq9TqQQ4zWRu3AAGLMa3eNG2g4XgQCAixAA))
