### ISSUE TITLE
Conditional attributes in Vento templates

### ISSUE THREAD

**Issue by noelforte** [g-plane/markup_fmt#22]
### Description
When there are directives in the tag of the markup, dprint fails to format.

```hbs
{{ set test = true }}

<p{{ if test }} class="my-class"{{ /if }}></p>
```

This works, but leaves behind an empty attribute.

```hbs
{{ set test = true }}

<p class="{{ if test }}my-class{{ /if }}"></p>
```

### Output of error
```sh
Error formatting /***/test.vto. 
Message: syntax error 'expect self close tag' at line 3, column 38
```

### Reduced test case
https://github.com/noelforte/dprint-vento-format-rtc

**Comment by g-plane** [comment]
That's one of known limitations when formatting Vento templates.
