### ISSUE TITLE
This plugin is awesome, but was hard to find 🤔

### ISSUE THREAD

**Issue by douglasg14b** [g-plane/markup_fmt#3]
Just FYI. This is awesome, but was really hard to find (For vue), maybe repo/plugin naming could help that? Or getting features on dprint as a plugin for things like Vue or Svelt?

**Comment by g-plane** [comment]
You can use this as a dprint plugin. What's your problem?

**Comment by douglasg14b** [comment]
No problem, just letting you know it was hard to find. Which means other may also pass this lib up mainly because they didn't discover it.

**Comment by g-plane** [comment]
I've asked dsherret in https://github.com/dprint/dprint/issues/492#issuecomment-1833053100 .

**Comment by g-plane** [comment]
This plugin has been added to dprint website, so this issue can be closed now.
