### ISSUE TITLE
Publish `dprint_plugin_markup` to crates.io

### ISSUE THREAD

**Issue by c12i** [g-plane/markup_fmt#35]
Hi,

Could you please publish the `dprint_plugin_markup` crate to crates.io? I need to call `format` from Rust to programmatically format code generated by my program. Having it available as a library on crates.io with the `format` method from the `MarkupFmtPluginHandler` struct public would make integration much easier.

Thanks.

**Comment by g-plane** [comment]
It has been already published to crates.io:

- [crates.io](https://crates.io/crates/markup_fmt)
- [docs.rs](https://docs.rs/markup_fmt)

**Comment by c12i** [comment]
Oh thanks, my bad, I was trying to add `dprint_plugin_markup` as a dependency directly. Closing
