### ISSUE TITLE
Failed to parse Jinja attribute starts with interpolation

### ISSUE THREAD

**Issue by g-plane** [g-plane/markup_fmt#46]
This seems to cause an issue for the following snippet that is not parsing anymore: 

```html
<picture
    {% for key, val in attributes.items %} 
        {{ key }}="{{ val }}"
    {% endfor %}
></picture>
```

I get this `Failed to parse "src/t.html" with error Syntax(SyntaxError { kind: ExpectJinjaTag, pos: 61, line: 3, column: 11 })`. This is failing to parse `{{ key }}` because it expect a JinjaTag.

_Originally posted by @UnknownPlatypus in https://github.com/g-plane/markup_fmt/issues/44#issuecomment-2305455805_

**Comment by UnknownPlatypus** [comment]
Thanks :raised_hands:
