### ISSUE TITLE
Astro comments are unnecessarily multiline

### ISSUE THREAD

**Issue by michaelhthomas** [g-plane/markup_fmt#51]
Currently, the following line:
```
{/* Comment */}
```

is formatted as 
```
{
  /* Comment */
}
```

in an Astro file. This is likely related more to the typescript plugin, just curious if there's any way to keep these on one line.

**Comment by g-plane** [comment]
I can't reproduce.

**Comment by michaelhthomas** [comment]
I'll try to publish a minimal reproduction.

**Comment by michaelhthomas** [comment]
Turns out this is a very specific case, and I'm a bit dumbfounded. The issue occurs when you have a comment expression containing two forward slashes (maybe these are being considered a comment as well?). In my case, this occurred because I included a URL in a comment. For example,

```astro
{/* Hello world */}
```

will not have any weird wrapping, but 

```astro
{/* https://example.com */}
```

will be formatted as 

```diff
- {/* https://example.com */}
+ {
+   /* https://example.com */
+ }
```

**Comment by g-plane** [comment]
markup_fmt doesn't know those two slashes are in comments, and they're treated as line comments, such as:

```typescript
{// xxx}
```

which causes wrapping.

**Comment by michaelhthomas** [comment]
Ah that makes sense. I feel like this is a bug, especially since afaik
```astro
{// comment}
```
isn't even valid syntax to begin with. Is it possible to have the parser keep track of whether it's already in a comment, and ignore the //?

**Comment by g-plane** [comment]
However this can be valid:

```typescript
{
  // comment
}
```

**Comment by g-plane** [comment]
It's a good idea for detecting this in parser.

**Comment by g-plane** [comment]
It seems that there is a GitHub bug when I was commenting.
