### ISSUE TITLE
Provide more structured data in `SyntaxError`

### ISSUE THREAD

**Issue by bartlomieju** [g-plane/markup_fmt#57]
I already opened https://github.com/g-plane/markup_fmt/pull/56 to have more granular control over how error messages are displayed.

It would be lovely if `SyntaxError` could provide additional information like "start" and "end" position (a "range") of the error (if that's possible) so that users of the crate could crate more rich error displays, something like `dprint-plugin-typescript` does:

```
Error formatting: /Users/ib/dev/deno/broken.ts
   Expected '{', got 'interface' at file:///Users/ib/dev/deno/broken.ts:1:8

  export interface Foo }{}
         ~~~~~~~~~
Checked 1 file

```

In this particular case we have a range that points to the "interface" keyword which is underlined.

**Comment by g-plane** [comment]
Source code is parsed directly without tokenizing/lexing, so it doesn't know where the end position is.

**Comment by bartlomieju** [comment]
Makes sense, I can just point to the concrete line/column without a range then :) any chance you could cut another release so I could leverage https://github.com/g-plane/markup_fmt/pull/56 and https://github.com/g-plane/markup_fmt/issues/58?

**Comment by g-plane** [comment]
https://github.com/g-plane/markup_fmt/releases/tag/v0.13.1

**Comment by g-plane** [comment]
https://github.com/g-plane/markup_fmt/releases/tag/v0.13.1
