### ISSUE TITLE
[Astro] Add all tests from `prettier-plugin-astro`

### ISSUE THREAD

**Issue by michaelhthomas** [g-plane/markup_fmt#62]
I've been trying to set up `markup_fmt` with a medium-size Astro codebase for the last few weeks, and keep noticing some subtle issues. Rather than address all of these individually, I think it would be great to create a branch containing all or most of the tests from the `prettier-plugin-astro` repository, then work to fix any discrepancies that arise. I would be more than happy to at least pull in all of the tests from the `prettier-plugin-astro` repository, though I'm not sure I'm qualified to actually fix bugs in the formatter. In any case, I would love to get your thoughts on this.

Another possibility would be to actually run prettier on the test files and compare the output. That way the output doesn't have to constantly be synced to get an idea of compatibility with prettier.

**Comment by g-plane** [comment]
Being compatible with Prettier isn't our goal, and never be.

**Comment by michaelhthomas** [comment]
Fair enough. I'd be more than happy to just raise bugs whenever something doesn't look like I'd expect, just figured it would be convenient to have a target to test against (provided that were the goal).
