### ISSUE TITLE
Code for external formatter gets strange indents

### ISSUE THREAD

**Issue by bartlomieju** [g-plane/markup_fmt#74]
This issue is somewhat related to https://github.com/dprint/dprint-plugin-typescript/issues/678 and https://github.com/denoland/deno/issues/26560.

Given this HTML file:
```html
<!DOCTYPE html>
<html lang="en">
  <body>
    <style>a { text-decoration: none; }</style>
    <style>
      a {
        text-decoration: none;
      }
      /* Next line is just 2 spaces */
  
      /* --- */
    </style>
    <script>window.addEventListener('load', () => {})</script>
  </body>
</html>
```
the external formatter gets called with following snippets:
```css


           a { text-decoration: none; }
```
```css




      a {
        text-decoration: none;
      }
      /* Next line is just 2 spaces */

      /* --- */
```
```js











            window.addEventListener('load', () => {})
```

Notice that all these snippets have several leading empty lines and they get "original" indentation - ie. the number of leading indents is equal to the amount of characters stripped from HTML tags. Then after these snippets are formatted by external formatter they are put back into relevant tags.

In case of `dprint-plugin-typescript` it tries to preserve indentation for things like comments which leads to "unstable" formatting in Deno (which verifies that formatting a file multiple times doesn't change the formatting output). 

I think this is not a great behavior and I believe the leading newlines and leading indentations should be removed, external formatter should be called and then `markup_fmt` should indent them back as necessary. This would make external formatters not need to understand the "context" from where these snippets are coming from and treat snippets as if they were standalone files.

@g-plane do you agree with this? If so I could try to open an PR and correct the behavior here.

**Comment by g-plane** [comment]
No, these whitespaces are added deliberately, which can be helpful when reporting syntax errors. You can think it's something like stripping TypeScript types in SWC or Node.js `--experimental-strip-types` flag: replace unrelated content with whitespaces to keep source location.

**Comment by bartlomieju** [comment]
Fair enough, we'll try to fix it in `dprint-plugin-typescript`.
