### ISSUE TITLE
Add astro support

### ISSUE THREAD

**Issue by millette** [g-plane/markup_fmt#8]
[Astro](https://astro.build/) support would be wonderful!

It's supported by prettier: <https://github.com/withastro/prettier-plugin-astro>

It's also in [biome plans](https://github.com/biomejs/biome/issues/1719).

**Comment by g-plane** [comment]
v0.4.0 is released with Astro support. Feel free to open new issues if you find bugs, also don't forget to give it a star and recommend this project to others.
