### ISSUE TITLE
PHP Formatting

### ISSUE THREAD

**Issue by trymeouteh** [g-plane/markup_fmt#81]
To add PSR-12 formatting for PHP code.

https://www.php-fig.org/psr/psr-12

Would go nicely with the HTML formatter since HTML code is allowed in PHP files.

https://github.com/dprint/dprint/issues/915

**Comment by g-plane** [comment]
This isn't this plugin's responsibility. PHP formatter should pick HTML code then call the "format with host" functionality, and once markup_fmt is installed, HTML code will be formatted.
