### ISSUE TITLE
Extend `Hints` to provide "file indent level" for external formatters

### ISSUE THREAD

**Issue by bartlomieju** [g-plane/markup_fmt#85]
With addition of https://github.com/dprint/dprint-plugin-typescript/pull/689 in `dprint-plugin-typescript`, it's possible to provide stable sorting of JS in `<script>` tags. To do that, we need to instruct `dprint-plugin-typescript` about the indentation level for that particular block. 

https://docs.rs/markup_fmt/latest/markup_fmt/struct.Hints.html is used to provide information about the "file extension" and the "print width"; could we please add another field that tells about the indentation level?

This would help close 5 different issues in Deno 😅

**Comment by g-plane** [comment]
Does the "indent level" means:

```html
<div>
  <div>
    <div>
    ^ indent level = 4
    </div>
  </div>
</div>
```

?

**Comment by dsherret** [comment]
It means the number of indents. Maybe we should come up with a better name, but I can't think of one atm.

```
<div>
^ indent level = 0
  <div>
  ^ indent level = 1 (1 indent)
    <script>
    ^ indent level = 2 (2 indents)
      console.log(1);
      ^ indent level = 3 (3 indents)
    </script>
  </div>
</div>
```

https://dprint.dev/playground/#code/MYewdgziA2CmB00QHMAUAWAlAbiA/config/N4WAUABBBEBmCWAbApgSQHYBNnoC4BlkA3ZRaALggBZwBfcIA/plugin/typescript
