### ISSUE TITLE
Formatting an Astro file with ", ', or ` in the component script can clear the file

### ISSUE THREAD

**Issue by kylemclean** [g-plane/markup_fmt#9]
I formatted the following file, which cleared the entirety of the component script and layout. It seems to have been caused by the `"'"` in the third line.

Input file `index.astro`:
```astro
---
const a = 1;
const b = "'";
const c = 2;
---

<html></html>
```

Output file:
```astro
---

---
```

The following input files also result in the same empty output file:
```astro
---
//'
---
```

```astro
---
//"
---
```

```astro
---
//`
---
```

Here is the `dprint.json` that was used:
```json
{
  "markup": {
  },
  "excludes": [
    "**/node_modules",
    "**/*-lock.json"
  ],
  "plugins": [
    "https://plugins.dprint.dev/g-plane/markup_fmt-v0.5.0.wasm"
  ]
}
```

The same behavior occurred with the TypeScript plugin added.

**Comment by g-plane** [comment]
v0.5.1 is released and it fixed this problem. Feel free to open new issues if you find bugs, also don't forget to give it a star and recommend this project to others.
