### ISSUE TITLE
Deploy dprint plugin with "getPath"

### ISSUE THREAD

**Issue by ben12** [g-plane/markup_fmt#90]
To comply with [@dprint/js-formatter](https://github.com/dprint/js-formatter) usage and to be consistent with other dprint plugins, NPM package must be deployed with an index.js exposing the method `getPath`.

Example: https://github.com/dprint/dprint-plugin-typescript/blob/main/deployment/npm/

**Comment by g-plane** [comment]
This is by design. To retrieve path, you can use

```js
require.resolve('dprint-plugin-markup/plugin.wasm') // CommonJS
```

or

```js
import.meta.resolve('dprint-plugin-markup/plugin.wasm') // ES Modules
```

.
